### ISSUE TITLE
Document usage with `.svelte`

### ISSUE THREAD

**Issue by dimaMachina** [antfu/eslint-processor-vue-blocks#7]
### Clear and concise description of the problem

I don't know if there is a similar package for extracting svelte's blocks, but [I did setup in graphql-eslint svelte example](https://github.com/dimaMachina/graphql-eslint/pull/2736) and it seems to work

### Suggested solution

Document that is possible to use with Svelte to extract their `<script>` tags content

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't know if I'd have time to maintain the Svelte compatibility, in that case I'd prefer to not document it that might give the illusion that it's supported. (I am glad it work, but just not a officially supported feature).
